Nina workout
wojtih/nina pull request #2
Opened 2017-04-27 10:55 UTC by shaolinxi

2017-04-27 11:46 UTC, wojtih requested changes
Dużo jakichś śmieciowych plików się dodało.

2017-04-27 11:46 UTC, wojtih commented on app/models/product.rb
> +   validates :boolean_new_product, inclusion: { in: [true, false] }
słowo boolean nie ma tutaj sensu w nazwie. Pole powinno się nazywać `new_product`

2017-04-27 11:46 UTC, wojtih commented on app/models/product.rb
> +   validates :catalogue_number, uniqueness: true, on: :create
Dlaczego tylko walidacja ma działać w przypadku tworzenia produktu a nie w przypadku edycji?

2017-04-27 11:46 UTC, wojtih commented on app/models/product.rb
> +   validates :name, length: { maximum: 50 }
Może trzeba też dodać walidacje `presence`

2017-04-27 11:46 UTC, wojtih commented on app/models/product.rb
> +   validates :country_of_origin, format: { with: /\A[a-zA-Z]+\z/,
Wiesz co to robi? :D

2017-04-27 11:46 UTC, wojtih commented on config/database.yml.example
> -default: &default
Dlaczego usunąłeś ten plik?

2017-04-27 15:44 UTC, shaolinxi commented on config/database.yml.example
> -default: &default
qrde ten plik usunąłem chyba jakoś zaraz po naszym pierwszym spotkaniu, wydaje mi się, że coś mi ten plik mieszał, ale to równie dobrze mogło mi się tylko wydawać...

2017-04-27 15:47 UTC, shaolinxi commented on app/models/product.rb
> +   validates :boolean_new_product, inclusion: { in: [true, false] }
to pomyłka chyba związana z późną godziną tworzenia - poprawione :)

2017-04-27 15:47 UTC, shaolinxi commented on app/models/product.rb
> +   validates :catalogue_number, uniqueness: true, on: :create
racja - poprawione

2017-04-27 15:47 UTC, shaolinxi commented on app/models/product.rb
> +   validates :name, length: { maximum: 50 }
dodane

2017-04-27 15:47 UTC, shaolinxi commented on app/models/product.rb
> +   validates :country_of_origin, format: { with: /\A[a-zA-Z]+\z/,
umożliwia wprowadzenie rekordu wyłącznie w postaci liter, czyż tak? :)

2017-04-27 23:04 UTC, wojtih requested changes

2017-04-27 23:04 UTC, wojtih commented on app/models/product.rb
> +   validates :catalogue_number, presence: true, uniqueness: true, on: :create and :update
Skoro i update i create to można to poprostu wywalić. Wtedy walidacja działa przy tworzeniu nowego i edycji istniejącego obiektu

2017-04-27 23:04 UTC, wojtih commented on config/database.yml.example
> -default: &default
To dodaj go proszę jeszcze raz. Treść możesz kopiować z tąd.

2017-04-27 23:04 UTC, wojtih commented on db/schema.rb
> +    t.string   "country_of_origin"
Dodaj jeszcze dla `new_product` i `name` warunek `null: false`.
Możesz dodać nowy plik migracji który to dodaje. 
Wygoogluj. `How to add null false to migraration rails` :)

2017-04-29 16:25 UTC, wojtih approved these changes

2017-04-29 16:26 UTC, merged